# Temel imaj olarak OpenJDK kullan
FROM openjdk:jdk-19

# Uygulama dosyasını ekle
#COPY C:\Users\User\Intellij Ultimate\ms-school-management

# Uygulamayı çalıştır
ENTRYPOINT ["java", "-jar", "/app.jar"]
